stages:
  - build
  - deploy
  - migrate

build_ardent:
  stage: build
  script:
    - cd agent
    - python setup.py bdist_wheel

deploy_production:
  stage: deploy
  environment:
    name: Production
    url: https://c2.veldt.me/
  only:
    - master
  script:
    - echo "Copying files to webroot"
    - rsync -av -delete . /var/www/C2-Framework/

migrate_make:
  stage: migrate
  environment:
    name: Production
    url: https://c2.veldt.me/
  only:
    - master
  script:
   - python /var/www/C2-Framework/manage.py makemigrations --settings=C2.settings.prod

migrate:
  stage: migrate
  environment:
    name: Production
    url: https://c2.veldt.me/
  only:
    - master
  script:
   - python /var/www/C2-Framework/manage.py migrate --settings=C2.settings.prod
