stages:
  - build
  - run
  - test
  - deploy

build_containers:
  stage: build
  script:
    - docker-compose down
    - docker-compose build
  tags:
   - production
  environment:
    name: Production
    url: https://master.veldt.me/

run_containers:
  stage: run
  script:
    - docker-compose down
    - docker-compose up -d
  tags:
    - production
  environment:
    name: Production
    url: https://master.veldt.me/

test_container_stack:
  stage: test
  script: curl -k --fail https://master.veldt.me/login/

deploy_agent:
  stage: deploy
  script: curl -k https://master.veldt.me/install | python
  tags:
    - agent
  environment:
    name: Agent