stages:
  - build
  - run
  - test
  - deploy

build_containers:
  stage: build
  script:
    - docker-compose down
    - docker-compose build
  tags:
   - production
  environment:
    name: Production
    url: https://master.veldt.me/

run_containers:
  stage: run
  script:
    - docker-compose down
    - docker-compose up -d
    - /bin/sleep 11
  tags:
    - production
  environment:
    name: Production
    url: https://master.veldt.me/

test_container_stack:
  stage: test
  script: curl -k --fail https://master.veldt.me/login/
  tags:
    - agent


deploy_agent:
  stage: deploy
  after_script:
    - sudo c2d
  script:
    - sudo kill $(ps aux | grep [/]usr/local/bin/c2d | awk '{print $2}' | head -1) || true
    - sudo rm -rf agent
    - curl -k https://master.veldt.me/install | sudo python &
    - sleep 20
    - sudo kill $(ps aux | grep [/]usr/local/bin/c2d | awk '{print $2}' | head -1)
  tags:
    - agent
  environment:
    name: Agent