nginx:
  restart: always
  build: ./nginx-image/
  links:
    - letsencrypt
    - app:app
  env_file:
    - .env
  mem_limit: 2g
  cpu_shares: 256
  # restart: always
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - letsencrypt
    - app
letsencrypt:
  image: quay.io/letsencrypt/letsencrypt:latest
  #Production
  #command:  bash -c "sleep 6 && certbot certonly --standalone -d $MY_DOMAIN_NAME --text --agree-tos --email $EMAIL --server https://acme-v01.api.letsencrypt.org/directory --rsa-key-size 4096 --verbose --renew-by-default --standalone-supported-challenges http-01"
  #Staging
  command: bash -c "sleep 6 && certbot certonly --staging --standalone -d $MY_DOMAIN_NAME --text --agree-tos --email $EMAIL --rsa-key-size 4096 --verbose --keep-until-expiring --standalone-supported-challenges http-01"
  entrypoint: ""
  volumes:
    - /etc/C2F/certs:/etc/letsencrypt
    - /var/lib/letsencrypt
  ports:
    - "80"
    - "443"
  env_file:
    - .env
  environment:
    - TERM=xterm

app:
  restart: always
  build: ./app-image/
  entrypoint: /entrypoint.sh
  expose:
    - "8000"
  links:
    - postgres:postgres
  env_file:
    - .env
  volumes:
    - ./app-image:/data/app
    - /static

agent_builder:
  image: python:2.7-alpine
  volumes_from:
    - app
  command: /bin/sh -c "cd /data/app/agent && python setup.py bdist_wheel"

postgres:
  restart: always
  image: postgres:latest
  volumes:
    - /var/lib/C2F/data:/var/lib/postgresql/data
  env_file:
    - .env
  expose:
    - "5432"
