# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-22 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_agent_os'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='id',
        ),
        migrations.AddField(
            model_name='agent',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9a088ee9-fe95-475c-a911-936c50688b38'), editable=False, primary_key=True, serialize=False),
        ),
    ]
