# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-22 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171122_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
