# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20171203_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=64)),
                ('container', models.TextField(max_length=256)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
