# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-20 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='os',
            field=models.TextField(default='Winblows', max_length=256),
            preserve_default=False,
        ),
    ]
