# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-03 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent_Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='NmapResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.TextField()),
                ('open_ports', models.TextField()),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Agent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='module',
            name='hash',
            field=models.TextField(default='0000000', max_length=256, unique=True),
        ),
        migrations.AddField(
            model_name='agent_module',
            name='module_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Module'),
        ),
    ]
